name: CI - PR Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up dbt
      run: |
        pip install dbt-bigquery
        
    - name: Set up Google Cloud credentials
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        
    - name: Run dbt tests (dev)
      run: |
        cd dbt/dog_breeds
        dbt test --target dev
        
    - name: Run dbt run (dev)
      run: |
        cd dbt/dog_breeds
        dbt run --target dev