name: CI - PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dbt
      run: |
        pip install dbt-bigquery
        
    - name: Set up Google Cloud credentials
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        
    - name: Create dbt profiles
      run: |
        mkdir -p ~/.dbt
        cat > ~/.dbt/profiles.yml << EOF
        dog_breeds:
          target: dev
          outputs:
            dev:
              type: bigquery
              method: service-account
              project: pyne-dog-breeds
              dataset: dev
              keyfile: /tmp/gcp_key.json
              location: EU
              threads: 1
        EOF
        
    - name: Copy GCP credentials
      run: |
        echo '${{ secrets.GCP_CREDENTIALS }}' > /tmp/gcp_key.json
        
    - name: Install dbt dependencies
      run: |
        cd pyne-dog-breeds/dbt/dog_breeds
        dbt deps
        
    - name: Run dbt tests (dev)
      run: |
        cd pyne-dog-breeds/dbt/dog_breeds
        dbt test --target dev
        
    - name: Run dbt run (dev)
      run: |
        cd pyne-dog-breeds/dbt/dog_breeds
        dbt run --target dev
