name: CI - PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dbt
      run: |
        pip install dbt-bigquery
        
    - name: Set up Google Cloud credentials
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        
    - name: Run dbt tests (dev)
      run: |
        cd pyne-dog-breeds/dbt/dog_breeds
        dbt test --target dev
        
    - name: Run dbt run (dev)
      run: |
        cd pyne-dog-breeds/dbt/dog_breeds
        dbt run --target dev